"resource/ui/#customizations/hud_customization_chat_position.res"
{
	"SafeMode"
	{
		"Customizations_Scroller"
		{
			"Chat_Position"
			{
				"ControlName"						"EditablePanel"
				"fieldName"							"Chat Position"
				"xpos"								"501"
				"ypos"								"165"
				"zpos"								"0"
				"wide"								"62"
				"tall"								"103"
				"visible"							"1"
				"enabled"							"1"
				"proportionaltoparent"				"1"
				"paintBackground"					"1"
				"paintBackgroundType"				"2"
				"roundedcorners"					"5"
				"bgcolor_override"					"FooterBGBlack"

				"Title"
				{
					"ControlName"						"CExLabel"
					"fieldName"							"Title"
					"xpos"								"0"
					"ypos"								"0"
					"zpos"								"0"
					"wide"								"f0"
					"tall"								"15"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"use_proportional_insets"			"1"
					"labelText"							"Chat Position"
					"font"								"ItemFontNameSmallest"
					"textAlignment"						"center"
					"textinsetx"						"5"
					"fgcolor"							"White"
					"paintbackground"					"1"
					"paintBackgroundType"				"2"
					"roundedcorners"					"3"
					"bgcolor_override"					"StoreGreen"
				}

				"Chat_Position_Top"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Chat_Position_Top"
					"xpos"								"3"
					"ypos"								"16"
					"zpos"								"20"
					"wide"								"56"
					"tall"								"28"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"
					"paintBackgroundType"				"0"
					"bgcolor_override"					"FooterBGBlack"

					"Chat_Position_Name"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Chat_Position_Name"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmallest"
						"labeltext"							"Top"
						"textAlignment"						"center"
						"fgcolor"							"TanLight"
						"paintbackground"					"0"
						"paintbackgroundtype"				"0"
					}

					"Chat_Position_Left"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Chat_Position_Left"
						"xpos"								"0"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"p0.31"
						"tall"								"16"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"L"
						"font"								"ItemFontNameSmall"
						"textAlignment"						"center"
						"command"							"engine hud_chat_position_top_left"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Chat_Position_Name"
						"pin_corner_to_sibling"				"PIN_TOPLEFT"
						"pin_to_sibling_corner"				"PIN_BOTTOMLEFT"

					}
					"Chat_Position_Center"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Chat_Position_Center"
						"xpos"								"0"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"p0.31"
						"tall"								"16"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"C"
						"font"								"ItemFontNameSmall"
						"textAlignment"						"center"
						"command"							"engine hud_chat_position_top_center"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Chat_Position_Name"
						"pin_corner_to_sibling"				"PIN_CENTER_TOP"
						"pin_to_sibling_corner"				"PIN_CENTER_BOTTOM"
					}
					"Chat_Position_Right"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Chat_Position_Center"
						"xpos"								"0"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"p0.31"
						"tall"								"16"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"R"
						"font"								"ItemFontNameSmall"
						"textAlignment"						"center"
						"command"							"engine hud_chat_position_top_right"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Chat_Position_Name"
						"pin_corner_to_sibling"				"PIN_TOPRIGHT"
						"pin_to_sibling_corner"				"PIN_BOTTOMRIGHT"
					}
				}

				"Chat_Position_Middle"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Chat_Position_Middle"
					"xpos"								"0"
					"ypos"								"0"
					"zpos"								"20"
					"wide"								"56"
					"tall"								"28"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"
					"paintBackgroundType"				"0"
					"bgcolor_override"					"FooterBGBlack"

					"pin_to_sibling"					"Chat_Position_Top"
					"pin_corner_to_sibling"				"PIN_CENTER_TOP"
					"pin_to_sibling_corner"				"PIN_CENTER_BOTTOM"

					"Chat_Position_Name"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Chat_Position_Name"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmallest"
						"labeltext"							"Middle"
						"textAlignment"						"center"
						"fgcolor"							"TanLight"
						"paintbackground"					"0"
						"paintbackgroundtype"				"0"
					}

					"Chat_Position_Left"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Chat_Position_Left"
						"xpos"								"0"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"p0.31"
						"tall"								"16"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"L"
						"font"								"ItemFontNameSmall"
						"textAlignment"						"center"
						"command"							"engine hud_chat_position_middle_left"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Chat_Position_Name"
						"pin_corner_to_sibling"				"PIN_TOPLEFT"
						"pin_to_sibling_corner"				"PIN_BOTTOMLEFT"

					}
					"Chat_Position_Center"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Chat_Position_Center"
						"xpos"								"0"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"p0.31"
						"tall"								"16"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"C"
						"font"								"ItemFontNameSmall"
						"textAlignment"						"center"
						"command"							"engine hud_chat_position_middle_center"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Chat_Position_Name"
						"pin_corner_to_sibling"				"PIN_CENTER_TOP"
						"pin_to_sibling_corner"				"PIN_CENTER_BOTTOM"
					}
					"Chat_Position_Right"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Chat_Position_Center"
						"xpos"								"0"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"p0.31"
						"tall"								"16"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"R"
						"font"								"ItemFontNameSmall"
						"textAlignment"						"center"
						"command"							"engine hud_chat_position_middle_right"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Chat_Position_Name"
						"pin_corner_to_sibling"				"PIN_TOPRIGHT"
						"pin_to_sibling_corner"				"PIN_BOTTOMRIGHT"
					}
				}

				"Chat_Position_Bottom"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Chat_Position_Bottom"
					"xpos"								"0"
					"ypos"								"0"
					"zpos"								"20"
					"wide"								"56"
					"tall"								"28"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"
					"paintBackgroundType"				"0"
					"bgcolor_override"					"FooterBGBlack"

					"pin_to_sibling"					"Chat_Position_Middle"
					"pin_corner_to_sibling"				"PIN_CENTER_TOP"
					"pin_to_sibling_corner"				"PIN_CENTER_BOTTOM"

					"Chat_Position_Name"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Chat_Position_Name"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmallest"
						"labeltext"							"Bottom"
						"textAlignment"						"center"
						"fgcolor"							"TanLight"
						"paintbackground"					"0"
						"paintbackgroundtype"				"0"
					}

					"Chat_Position_Left"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Chat_Position_Left"
						"xpos"								"0"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"p0.31"
						"tall"								"16"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"L"
						"font"								"ItemFontNameSmall"
						"textAlignment"						"center"
						"command"							"engine hud_chat_position_bottom_left"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Chat_Position_Name"
						"pin_corner_to_sibling"				"PIN_TOPLEFT"
						"pin_to_sibling_corner"				"PIN_BOTTOMLEFT"

					}
					"Chat_Position_Center"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Chat_Position_Center"
						"xpos"								"0"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"p0.31"
						"tall"								"16"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"C"
						"font"								"ItemFontNameSmall"
						"textAlignment"						"center"
						"command"							"engine hud_chat_position_bottom_center"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Chat_Position_Name"
						"pin_corner_to_sibling"				"PIN_CENTER_TOP"
						"pin_to_sibling_corner"				"PIN_CENTER_BOTTOM"
					}
					"Chat_Position_Right"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Chat_Position_Center"
						"xpos"								"0"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"p0.31"
						"tall"								"16"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"R"
						"font"								"ItemFontNameSmall"
						"textAlignment"						"center"
						"command"							"engine hud_chat_position_bottom_right"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Chat_Position_Name"
						"pin_corner_to_sibling"				"PIN_TOPRIGHT"
						"pin_to_sibling_corner"				"PIN_BOTTOMRIGHT"
					}
				}
			}
		}
	}
}