"resource/ui/#customizations/hud_customization_chat_position.res"
{
	"SafeMode"
	{
		"Customizations_Scroller"
		{
			"Chat_Position"
			{
				"ControlName"						"EditablePanel"
				"fieldName"							"Chat Position"
				"xpos"								"501"
				"ypos"								"165"
				"zpos"								"0"
				"wide"								"62"
				"tall"								"145"
				"visible"							"1"
				"enabled"							"1"
				"proportionaltoparent"				"1"
				"paintBackground"					"1"
				"paintBackgroundType"				"2"
				"roundedcorners"					"5"
				"bgcolor_override"					"FooterBGBlack"

				"Title"
				{
					"ControlName"						"CExLabel"
					"fieldName"							"Title"
					"xpos"								"0"
					"ypos"								"0"
					"zpos"								"0"
					"wide"								"f0"
					"tall"								"15"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"use_proportional_insets"			"1"
					"labelText"							"Chat Position"
					"font"								"ItemFontNameSmallest"
					"textAlignment"						"center"
					"textinsetx"						"5"
					"fgcolor"							"White"
					"paintbackground"					"1"
					"paintBackgroundType"				"2"
					"roundedcorners"					"3"
					"bgcolor_override"					"StoreGreen"
				}

				"Chat_Position_Default"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Chat_Position_Default"
					"xpos"								"3"
					"ypos"								"16"
					"zpos"								"20"
					"wide"								"56"
					"tall"								"f82"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"
					"paintBackgroundType"				"0"
					"bgcolor_override"					"FooterBGBlack"

					"Chat_Position_Name"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Chat_Position_Name"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmallest"
						"labeltext"							"Default"
						"textAlignment"						"center"
						"fgcolor"							"TanLight"
						"paintbackground"					"0"
						"paintbackgroundtype"				"0"
					}
					"Chat_Position_Image"
					{
						"ControlName"						"ImagePanel"
						"fieldName"							"Chat_Position_Image"
						"xpos"								"cs-0.5"
						"ypos"								"cs-0.5+7"
						"zpos"								"6"
						"wide"								"44"
						"tall"								"40"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"scaleImage"						"1"
						"proportionaltoparent"				"1"
						// TODO: ADD IMAGE
						"image"								""
					}
					"Chat_Position_Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Chat_Position_Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"font"								""
						"command"							"engine hud_chat_position_default"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
					}
				}

				"Chat_Position_Center"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Chat_Position_Center"
					"xpos"								"0"
					"ypos"								"0"
					"zpos"								"20"
					"wide"								"56"
					"tall"								"f82"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"
					"paintBackgroundType"				"0"
					"bgcolor_override"					"FooterBGBlack"

					"pin_to_sibling"					"Chat_Position_Default"
					"pin_corner_to_sibling"				"PIN_TOPLEFT"
					"pin_to_sibling_corner"				"PIN_BOTTOMLEFT"

					"Chat_Position_Title"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Chat_Position_Title"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"zpos"								"1"
						"wide"								"f0"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmallest"
						"labeltext"							"Center"
						"textAlignment"						"center"
						"fgcolor"							"TanLight"
						"paintbackground"					"0"
						"paintbackgroundtype"				"0"
					}
					"Chat_Position_Image"
					{
						"ControlName"						"ImagePanel"
						"fieldName"							"Chat_Position_Image"
						"xpos"								"cs-0.5"
						"ypos"								"cs-0.5+7"
						"zpos"								"6"
						"wide"								"44"
						"tall"								"40"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"scaleImage"						"1"
						"proportionaltoparent"				"1"
						// TODO: ADD IMAGE
						"image"								""
					}
					"Chat_Position_Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Chat_Position_Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"5"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"font"								""
						"command"							"engine hud_chat_position_center"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
					}
				}
			}
		}
	}
}